//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTS.HELPS.WebServices.DataAccess
{
    using System;
    
    public partial class SessionType
    {
        public int id { get; set; }
        public string abbName { get; set; }
        public string fullName { get; set; }
        public Nullable<bool> iscurrent { get; set; }
    }
}
